name: CI Tests
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  CI-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install pipenv and dependencies
        run: pip install pipenv
          pipenv sync

      - name: Run tests
        run: pipenv run make test
